import React, { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { X, FileText, CheckSquare, Square, Download, Loader2 } from "lucide-react";
import { jsPDF } from "jspdf";
import "jspdf-autotable";

export const ExportPDFModal = ({ isOpen, onClose, items, categoryName }) => {
  const [selectedIds, setSelectedIds] = useState([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [spacing, setSpacing] = useState(5);
  const [margin, setMargin] = useState(10);
  const [useWatermark, setUseWatermark] = useState(true);

  useEffect(() => {
    if (isOpen) {
      setSelectedIds(items.map((item) => item._id));
    }
  }, [isOpen, items]);

  const toggleSelectAll = () => {
    if (selectedIds.length === items.length) {
      setSelectedIds([]);
    } else {
      setSelectedIds(items.map((item) => item._id));
    }
  };

  const toggleItem = (id) => {
    setSelectedIds((prev) =>
      prev.includes(id) ? prev.filter((i) => i !== id) : [...prev, id]
    );
  };

  const drawWatermark = (doc) => {
    if (!useWatermark) return;
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    
    doc.saveGraphicsState();
    doc.setGState(new doc.GState({ opacity: 0.1 }));
    doc.setFont("helvetica", "bold");
    doc.setFontSize(60);
    doc.setTextColor(150, 150, 150);
    
    // Rotate and draw in center
    doc.text("STUDY NOTES", pageWidth / 2, pageHeight / 2, {
      align: "center",
      angle: 45
    });
    
    // Small brand at bottom right
    doc.setFontSize(10);
    doc.text("Generated by StudyNotes", pageWidth - 10, pageHeight - 10, {
      align: "right"
    });
    
    doc.restoreGraphicsState();
  };

  const generatePDF = async () => {
    if (selectedIds.length === 0) return;
    setIsGenerating(true);

    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const contentWidth = pageWidth - (margin * 2);
      let yPos = margin + 10;

      const addPageWithWatermark = () => {
        doc.addPage();
        drawWatermark(doc);
        yPos = margin + 10;
      };

      // Initial page watermark
      drawWatermark(doc);

      // Title
      doc.setFontSize(22);
      doc.setTextColor(79, 70, 229); // Indigo-600
      doc.text(`${categoryName} Notes`, margin, yPos);
      yPos += 12;

      const selectedItems = items.filter((item) => selectedIds.includes(item._id));

      selectedItems.forEach((item, index) => {
        // Check for page break before starting a new item
        if (yPos > pageHeight - 40) {
          addPageWithWatermark();
        }

        // Question / Title (Bold)
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(30, 41, 59); // Slate-800
        const titleLines = doc.splitTextToSize(`${index + 1}. ${item.title}`, contentWidth);
        doc.text(titleLines, margin, yPos);
        yPos += titleLines.length * 5.5 + 1; // Reduced line height and gap (1px)

        // Description (if exists)
        if (item.description) {
            doc.setFontSize(10);
            doc.setFont("helvetica", "italic");
            doc.setTextColor(100, 116, 139); // Slate-500
            const descLines = doc.splitTextToSize(item.description, contentWidth);
            doc.text(descLines, margin, yPos);
            yPos += descLines.length * 4.5 + 1; // Reduced line height and gap (1px)
        }

        // Answer / Solution
        doc.setFontSize(10.5);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(51, 65, 85); // Slate-700
        
        let content = "";
        if (item.type === "dsa") {
           content = item.solutions.map(s => `[${s.label}]\n${s.code}`).join('\n\n');
        } else {
           content = item.answer || "";
        }

        // Basic Markdown-like code block detection and rendering
        const parts = content.split(/(```[\s\S]*?```)/g);
        
        parts.forEach(part => {
            if (part && part.startsWith("```")) {
                // Code block
                const code = part.replace(/```(\w+)?\n?/, "").replace(/```$/, "").trim();
                doc.setFont("courier", "normal");
                doc.setFontSize(9);
                doc.setTextColor(37, 99, 235); // Blue-600
                
                const codeLines = doc.splitTextToSize(code, contentWidth - 10);
                // Draw a light background for code block
                const blockHeight = codeLines.length * 5 + 4;
                if (yPos + blockHeight > pageHeight - margin) {
                    addPageWithWatermark();
                }
                
                doc.setFillColor(248, 250, 252); // Slate-50
                doc.rect(margin - 2, yPos - 4, contentWidth + 4, blockHeight, 'F');
                
                codeLines.forEach(line => {
                    doc.text(line, margin, yPos);
                    yPos += 5;
                });
                yPos += 4;
                doc.setFont("helvetica", "normal");
                doc.setFontSize(10.5);
                doc.setTextColor(51, 65, 85);
            } else if (part && part.trim()) {
                // Normal text
                doc.setFont("helvetica", "normal");
                const textLines = doc.splitTextToSize(part.trim(), contentWidth);
                textLines.forEach(line => {
                    if (yPos > pageHeight - margin) {
                        addPageWithWatermark();
                    }
                    doc.text(line, margin, yPos);
                    yPos += 5.5;
                });
            }
        });

        yPos += spacing; // Use adjustable spacing
      });

      doc.save(`${categoryName.replace(/\s+/g, '_')}_Notes.pdf`);
    } catch (error) {
      console.error("PDF generation error:", error);
    } finally {
      setIsGenerating(false);
      onClose();
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[60] flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm">
      <motion.div
        initial={{ opacity: 0, scale: 0.95, y: 20 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.95, y: 20 }}
        className="bg-white dark:bg-slate-900 w-full max-w-2xl rounded-3xl shadow-2xl border border-slate-200 dark:border-slate-800 overflow-hidden flex flex-col max-h-[90vh]"
      >
        {/* Header */}
        <div className="p-6 border-b border-slate-100 dark:border-slate-800 flex items-center justify-between bg-slate-50/50 dark:bg-slate-800/50">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-indigo-500/10 flex items-center justify-center">
              <FileText className="text-indigo-600 dark:text-indigo-400" size={24} />
            </div>
            <div>
              <h2 className="text-xl font-bold text-slate-800 dark:text-white leading-tight">Export PDF</h2>
              <p className="text-sm text-slate-500 dark:text-slate-400 font-medium">{categoryName}</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 hover:bg-slate-200 dark:hover:bg-slate-700 rounded-xl transition-colors text-slate-400 hover:text-slate-600 dark:hover:text-slate-200"
          >
            <X size={20} />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6 space-y-6 custom-scrollbar">
          
          {/* Controls */}
          <div className="grid grid-cols-2 gap-4 p-4 bg-slate-50 dark:bg-slate-800/50 rounded-2xl border border-slate-100 dark:border-slate-800">
            <div className="space-y-1.5 col-span-2 sm:col-span-1">
              <label className="text-[11px] font-black uppercase text-slate-400 tracking-wider">
                Item Spacing (px)
              </label>
              <input
                type="number"
                value={spacing}
                onChange={(e) => setSpacing(Number(e.target.value))}
                min="0"
                max="100"
                className="w-full px-3 py-2 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-xl text-sm focus:ring-2 focus:ring-indigo-500/20 outline-none transition-all"
              />
            </div>

            <div className="space-y-1.5 col-span-2 sm:col-span-1 flex items-end pb-2">
              <label className="flex items-center gap-2 cursor-pointer group">
                <input
                  type="checkbox"
                  checked={useWatermark}
                  onChange={(e) => setUseWatermark(e.target.checked)}
                  className="w-4 h-4 rounded border-slate-300 text-indigo-600 focus:ring-indigo-500 transition-all cursor-pointer"
                />
                <span className="text-[11px] font-black uppercase text-slate-400 tracking-wider group-hover:text-slate-600 dark:group-hover:text-slate-200 transition-colors">
                  Include Brand Watermark
                </span>
              </label>
            </div>
          </div>

          <div className="flex items-center justify-between mb-2">
            <span className="text-sm font-semibold text-slate-600 dark:text-slate-400">
              {selectedIds.length} of {items.length} items selected
            </span>
            <button
              onClick={toggleSelectAll}
              className="text-sm font-bold text-indigo-600 dark:text-indigo-400 hover:underline flex items-center gap-1.5"
            >
              {selectedIds.length === items.length ? (
                <><Square size={16} /> Deselect All</>
              ) : (
                <><CheckSquare size={16} /> Select All</>
              )}
            </button>
          </div>

          <div className="grid gap-2">
            {items.map((item) => (
              <button
                key={item._id}
                onClick={() => toggleItem(item._id)}
                className={`flex items-center gap-4 p-4 rounded-2xl border transition-all text-left ${
                  selectedIds.includes(item._id)
                    ? "border-indigo-500 bg-indigo-50/50 dark:bg-indigo-500/5 ring-1 ring-indigo-500/20"
                    : "border-slate-100 dark:border-slate-800 hover:border-slate-300 dark:hover:border-slate-700 bg-white dark:bg-slate-900 shadow-sm"
                }`}
              >
                <div className={`w-5 h-5 rounded flex items-center justify-center border transition-colors ${
                  selectedIds.includes(item._id)
                    ? "bg-indigo-600 border-indigo-600 text-white"
                    : "border-slate-300 dark:border-slate-600"
                }`}>
                  {selectedIds.includes(item._id) && <CheckSquare size={14} className="fill-current" />}
                </div>
                <div className="flex-1 overflow-hidden">
                  <h3 className="font-semibold text-slate-800 dark:text-slate-200 truncate capitalize">{item.title}</h3>
                  <p className="text-xs text-slate-500 dark:text-slate-400 truncate mt-0.5">{item.description || "No description"}</p>
                </div>
              </button>
            ))}
          </div>
        </div>

        {/* Footer */}
        <div className="p-6 border-t border-slate-100 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-800/50">
          <button
            onClick={generatePDF}
            disabled={selectedIds.length === 0 || isGenerating}
            className={`w-full py-4 rounded-2xl flex items-center justify-center gap-2 font-bold text-white transition-all shadow-lg shadow-indigo-500/25 ${
              selectedIds.length === 0 || isGenerating
                ? "bg-slate-400 cursor-not-allowed opacity-70"
                : "bg-indigo-600 hover:bg-indigo-700 active:scale-[0.98]"
            }`}
          >
            {isGenerating ? (
              <><Loader2 className="animate-spin" size={20} /> Generating PDF...</>
            ) : (
              <><Download size={20} /> Download PDF</>
            )}
          </button>
        </div>
      </motion.div>
    </div>
  );
};
